### PR TITLE
remove app/bower_components

### PR DESCRIPTION
**Pull request by elmiko**
This change removes the installation files for the bower components and
adds `app/bower_components` to the ignore file. These files will get
regenerated for each install.

### CODE REVIEW

**Comment by sub-mod** [comment]
OK for now, since current bower components have latest versions.
post https://github.com/radanalyticsio/oshinko-webui/pull/25
the bower components will be much older.Considering the delicate balance libs for version compatibility, It is my opinion that the bower folders should not be removed in the future.

**Comment by crobby** [comment]
But, we do specify the exact versions to fetch in bower.json, so we can still manage our versions for compatibility.

**Comment by elmiko** [comment]
i think we should specify the versions then, what happens currently if you do an image build? will the bower install command overwrite anything installed in the bower_components directory or will it leave those versions?

**Comment by crobby** [comment]
I believe it would just install the specified version.  I'll do a little poking around to see what exactly the behavior is.  I don't think any app should keep bower_components in their git as it defeats the purpose of using bower.  That directory only existed in our git as a convenience to me in the early stages of development so I didn't have to keep watching the bower install.

**Comment by crobby** [comment]
Any objections to merging this?

**Pull request merged**
